typography_spectrum: 0.22218
color:
  brandColors:
    - '#fefefe'
    - '#090909'
    - '#464646'
    - '#a4a4a4'
    - '#7a7a7a'
  brandStrength: 0.5
  lightness: 0.5847049220465124
  saturation: 0.25
  rhythmicContrast: 0.8318869988434017
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.99815
analytics:
  google: null
  facebook: null
  twitter: null
name: jeffsteadman
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'This is my site. There are many like it, but this one is mine.'
purpose: []
