name: jeffsteadman
favicon: null
layout_spectrum: 0.7380734526086599
typography_spectrum: 0.08080044318921864
title: 'This is my site. There are many like, but this one is mine.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6022382145747542
  lightness: 0.5847049220465124
  saturation: 0.36151612806133926
  rhythmicContrast: 0.8318869988434017
purpose: []
