name: jeffsteadman
favicon: null
layout_spectrum: 0.99815
typography_spectrum: 0.22218
title: 'This is my site. There are many like, but this one is mine.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#090909'
    - '#464646'
    - '#a4a4a4'
    - '#7a7a7a'
  brandStrength: 0.5
  lightness: 0.5847049220465124
  saturation: 0.25
  rhythmicContrast: 0.8318869988434017
purpose: []
